### ISSUE TITLE
Omit Ambilight sat/hue logging

### ISSUE THREAD

**Issue by jarretc** [StijnOostdam/Winleafs#40]
When the refresh rate is set to 10 and using Ambilight, depending upon the source content its logging about 1mb of data every ~7 minutes. Would it be possible to silence the logging for the sat/hue updates but record all other logging such as when the settings are changed?

**Comment by StijnOostdam** [comment]
Thanks for the suggestion! By default every API call is logged and we do not have a function yet to omit the logs for certain calls. I will implement this function for the next version.
