### ISSUE TITLE
[Feature Request] connect multiple Nanoleaf Panels 

### ISSUE THREAD

**Issue by FiesoDuck** [StijnOostdam/Winleafs#41]
Hi, 
it would be really nice to be able to connect multiple Nanoleaf Panels with the ability

-  to mirror one of the panels

or 

- to be individualy controllable e.g. brightness and color scheme

Thanks for your work!

**Comment by StijnOostdam** [comment]
Hey, we are planning to go for the second option. Each device can have its own schedules. This feature is definitly something we are going to include in the next release. No promises on when that is though.

**Comment by FiesoDuck** [comment]
Great to hear and take your time with it. Looking forward to it.

**Comment by StijnOostdam** [comment]
Keep an eye out for updates on this issue. Maybe you could help us testing since we both do not have more than 1 set of panels.

**Comment by FiesoDuck** [comment]
Sure thing!

**Comment by StijnOostdam** [comment]
Hey, I just added support for adding multiple devices in this pre-release: https://github.com/StijnOostdam/Winleafs/releases/tag/v0.3. Could you please test this version and see if it works? I have thought of everything hopefully but testing it for real is impossible for me.

**Comment by FiesoDuck** [comment]
I just set it up and at a glance it is working flawlessly. Tomorrow i will test it more in depth. Thanks for the fast update!

**Comment by StijnOostdam** [comment]
Awesome! This is just basic functionality, where you can add schedules per device and override per device. If you have any suggestions, please let me know.

**Comment by FiesoDuck** [comment]
I am particular interested in the ambilight function and it is working perfectly. I am testing it with [subnautica ](https://unknownworlds.com/subnautica/)and it looks amazing. 

Is it possible to auto-select and activate the last setting on application launch / windows boot? Something like "use last setting" so i dont have to switch the lights on manually every time i boot my pc.

Also is it possible to control the brightness dynamically in the ambilight setting?

**Comment by bartdebever** [comment]
Unfortunately for now it's not possible to ambilight dynamically. We would love to work this into the application at some point but in the current state of ambilight it's not possible

**Comment by StijnOostdam** [comment]
@bartdebever I think @FiesoDuck means that the brightness automatically adjusts to how dark/light the screen is and I believe this is fairly easy to implement.

@FiesoDuck With auto-select and activate last setting, do you mean the override functionality?

**Comment by FiesoDuck** [comment]
> @bartdebever I think @FiesoDuck means that the brightness automatically adjusts to how dark/light the screen is and I believe this is fairly easy to implement.

Yes, thats what i meant.

@FiesoDuck With auto-select and activate last setting, do you mean the override functionality?

Correct.

**Comment by StijnOostdam** [comment]
Thanks, added both suggestions to the backlog

**Comment by StijnOostdam** [comment]
@FiesoDuck It would be great if you could take a picture of Subnautica in combination with the ambilight, we could put that in our project readme as a kind of showcasing.

**Comment by FiesoDuck** [comment]
@StijnOostdam I'll see what I can come up with :)

**Comment by StijnOostdam** [comment]
@FiesoDuck So I updated the ambilight effect to be more efficient. In the version you are using, every device has its own screen grabber, which is using CPU power it shouldn't be using. I updated so that only 1 screen grabber is active at all times and multiple devices can just get the screenshot from that. What I would like you to specifically test is the following:

- Enable ambilight on both devices and Winleafs should use a maximum of 10% CPU (check in task manager)
- Disable ambilight on 1 of your devices and the CPU usage should stay the same
- Disable ambilight on the second device and the CUP usage of Winleafs should drop to around 0%.

Could you please confirm this works? Then I can prepare for an official release of 0.3 :) The new installer can be found here: https://github.com/StijnOostdam/Winleafs/releases/tag/v0.3

**Comment by FiesoDuck** [comment]
I will test this and report back as soon as I am back home.

Stijn Oostdam <notifications@github.com> schrieb am Fr., 22. Feb. 2019,
22:25:

**Comment by StijnOostdam** [comment]
Great!

**Comment by FiesoDuck** [comment]
> * Enable ambilight on both devices and Winleafs should use a maximum of 10% CPU (check in task manager)
CPU usage between 3,5C - 7%

> * Disable ambilight on 1 of your devices and the CPU usage should stay the same
Confirmed, CPU usage stays the same.

> * Disable ambilight on the second device and the CPU usage of Winleafs should drop to around 0%.

Confirmed, CPU usage at 0% when ambilight is disabled.

**Comment by StijnOostdam** [comment]
Thank you! Then this is done.
