### ISSUE TITLE
Panel not able to reconnect

### ISSUE THREAD

**Issue by FiesoDuck** [StijnOostdam/Winleafs#50]
I ran into the issue that one of two panels, that was already configured earlier, would not respond to inputs / failed to connect. I was able to add this panel again using the "add device" button.  By then i could not remove the previous one. Only the newer was able to connect. 

I think the ip of the panel did change since last usage.

**Comment by StijnOostdam** [comment]
Thanks for the heads up. This does mean that we need to make a function to remove panels as you requested in #49.
