### ISSUE TITLE
Update window appears each time on launch with latest version

### ISSUE THREAD

**Issue by rowak** [StijnOostdam/Winleafs#53]

**Comment by StijnOostdam** [comment]
I know... I released v0.3.2 in the hope it would fix it, but it is not fixed. @bartdebever can you fix this?

**Comment by bartdebever** [comment]
Hopefully dedicating time to this issue this week.

**Comment by StijnOostdam** [comment]
v0.3.2 release should now have the correct installer. @rowak please close this issue if it is fixed.

**Comment by StijnOostdam** [comment]
Fixed as of v0.4 for sure
